// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJbIgB2_SxMjCOGsXi2mU23RiBBKQ_u3U',
    appId: '1:274746786337:web:4e6fc6b2aa6fc18a9ed960',
    messagingSenderId: '274746786337',
    projectId: 'ase456-individual-projec-59863',
    authDomain: 'ase456-individual-projec-59863.firebaseapp.com',
    storageBucket: 'ase456-individual-projec-59863.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7nX6BNlZbyVzvh3_Jxq8cbYzeD6OolVY',
    appId: '1:274746786337:android:9e87adb01292be899ed960',
    messagingSenderId: '274746786337',
    projectId: 'ase456-individual-projec-59863',
    storageBucket: 'ase456-individual-projec-59863.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0wKAIK3QiyOAcaLGf62T-f_6ETHYW1Mo',
    appId: '1:274746786337:ios:ef02718efd496d0e9ed960',
    messagingSenderId: '274746786337',
    projectId: 'ase456-individual-projec-59863',
    storageBucket: 'ase456-individual-projec-59863.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0wKAIK3QiyOAcaLGf62T-f_6ETHYW1Mo',
    appId: '1:274746786337:ios:5ea20880c429941f9ed960',
    messagingSenderId: '274746786337',
    projectId: 'ase456-individual-projec-59863',
    storageBucket: 'ase456-individual-projec-59863.appspot.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
